#!/bin/bash

if [ ! -f /.dockerenv ]; then
    echo '🚨  Do not run it outside a Docker container.' 1>&2
    exit 1
fi

host_uid=$(ls -n $0 | awk '{print $3}') # study who my owner is
host_gid=$(ls -n $0 | awk '{print $4}') # study what I belong to

# Create a user which has the common uid:gid with the host
# TODO: if the user with the uid already exists,
#       assign the name of user to `user`.
user=app
groupadd --gid $host_gid $user
useradd --uid $host_uid --gid $host_gid --shell /bin/bash $user

# Add some default files to the home
# note: it's needed because the volumes might be mounted before `useradd`.
mkdir -p /home/$user
cp -r /etc/skel/. /home/$user
chown $user:$user /home/$user /home/$user/.bash* /home/$user/.profile

# Execute the command left, or enter `bash`
if [ $# -gt 0 ]; then
    exec su-exec $user $@
else
    exec su-exec $user bash
fi
