#!/bin/bash

cd "$(dirname "$0")/.." # move to the parent dir
dirpath="$( pwd -P )" # study the dir path
project=${dirpath##*/} # set the name of dir

docker run \
  --name $project-mongo-client \
  --interactive --tty --rm \
  --network $project \
  mongo:3.2.21 \
  mongo --host=$project-mongod $@
