#!/bin/bash

mongo_version="3.2.21"
mysql_version="5.6"
app_dir="/app"
home_dir="/home/app"

cd "$(dirname "$0")/.." # move to the parent dir
dirpath="$( pwd -P )" # study the dir path
project=${dirpath##*/} # set the name of dir

#
# Starting up...
#
docker network create $project > /dev/null

docker run \
  --name $project-mongod \
  --detach --rm \
  --network $project \
  mongo:$mongo_version --replSet "rs0" > /dev/null

docker run \
  --name $project-mysqld \
  --detach --rm \
  --network $project \
  --env MYSQL_ALLOW_EMPTY_PASSWORD=yes \
  mysql:$mysql_version > /dev/null

# Build dev image
if [ -z "$(docker image ls -q $project-app)" ]; then
  bash dev/build
fi

# Initialize databases
echo -n "Waiting mysql."
while ! docker exec $project-mysqld mysqladmin ping --silent > /dev/null; do
  echo -n .
  sleep 1
done
echo " OK."
docker exec $project-mongod mongo --eval 'rs.initiate()' > /dev/null
docker exec $project-mysqld mysql -e "CREATE DATABASE momy;" > /dev/null

# Run dev container
docker run \
  --name $project-app \
  --interactive --tty --rm \
  --network $project \
  --env SSH_AUTH_SOCK=/ssh-agent \
  --mount type=bind,source=$SSH_AUTH_SOCK,target=/ssh-agent \
  --mount type=bind,source=$dirpath,target=$app_dir \
  --mount type=bind,source="$HOME/.ssh",target="$home_dir/.ssh" \
  --mount type=bind,source="$HOME/.gitconfig",target="$home_dir/.gitconfig" \
  $project-app $@

#
# Shutting down...
#
docker stop $project-mysqld > /dev/null
docker stop $project-mongod > /dev/null
docker network rm $project > /dev/null
